apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: whiteboard-gateway
  namespace: default
spec:
  gatewayClassName: nginx
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: whiteboard-route
  namespace: default
  labels:
    route: whiteboard-route
spec:
  parentRefs:
    - name: whiteboard-gateway
  hostnames:
    - "localhost"
  rules:
    - matches:
        - path:
            type: Prefix
            value: "/api"
      backendRefs:
        - name: tldraw-server-service
          port: 5858
    - matches:
        - path:
            type: Prefix
            value: "/"
      backendRefs:
        - name: tldraw-client-service
          port: 5757
