apiVersion: v1
kind: Service
metadata:
  name: tldraw-server
  labels:
    app: tldraw-server
spec:
  selector:
    app: tldraw-server
  ports:
    - protocol: TCP
      port: 5858
      targetPort: 5858
  type: ClusterIP
