apiVersion: apps/v1
kind: Deployment
metadata:
  name: tldraw-client
  labels:
    app: tldraw-client
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: tldraw-client
  template:
    metadata:
      labels:
        app: tldraw-client
    spec:
      containers:
        - name: tldraw-client
          imagePullPolicy: Never
          image: tldraw-client:1.0.0
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          ports:
          - containerPort: 5757
          env:
          - name: VITE_APP_UI_PORT
            value: '5757'
          - name: VITE_WORKER_URL
            value: 'http://localhost/api'
          - name: VITE_HOST
            value: '0.0.0.0'
        # For Prometheus monitoring
        - name: node-exporter
          image: quay.io/prometheus/node-exporter:latest
          args:
            - --web.listen-address=:9100
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+)($|/)
          ports:
            - containerPort: 9100
              name: metrics
          resources:
            limits:
              cpu: "100m"
              memory: "64Mi"
          volumeMounts:
            - name: host
              mountPath: /host
              readOnly: true
      volumes:
        - name: host
          hostPath:
            path: /